---
title: "DADA2_OSDV9"
author: "Camilo Gálvez A."
output: html_document
---

##Libraries
```{r echo=TRUE,message=FALSE,warning=FALSE,include=FALSE}
library(tidyverse)
library(BiocGenerics)
library(ShortRead)
library(dada2)
library(Biostrings)
library(DECIPHER)
```

```{r echo=TRUE,message=FALSE,warning=FALSE}
esteban <- read.table("D:/Documents/GitHub/CORE/Camilo/Meta/Estebaaan/ASV.sqs.txt", stringsAsFactors = FALSE)
taxa.pr414 <- assignTaxonomy(seqs = esteban[,1], 
                             refFasta = "X:/Documents/Proyectos_R/IDTAXA/data/pr2_version_4.14.0_SSU_dada2.fasta.gz", minBoot = 100, 
                             taxLevels = c("Kingdom", "Supergroup", "Division", "Class", "Order", "Family", "Genus", "Species"), 
                             multithread = TRUE, 
                             verbose = TRUE)
write.csv2(taxa.pr414, "D:/Documents/GitHub/CORE/Camilo/Meta/Estebaaan/taxa_pr414.csv")
```

```{r echo=TRUE,message=FALSE,warning=FALSE}
asv_seqs <- colnames(seqtab.nochim)
asv_headers <- vector(dim(seqtab.nochim)[2], mode = "character")

for (i in 1:dim(seqtab.nochim)[2]) {
  asv_headers[i] <- paste(">ASV", i, sep = "_")
}

#making and writing out a fasta of our final ASV seqs:
asv_fasta <- c(rbind(asv_headers, asv_seqs))
write(asv_fasta, "/Documents/GitHub/CORE/Camilo/Global/OSDV9/seqs_OSDV9.fasta") #Will be send to dropbox, not sure if push to dataset repository

#count table
asv_tab <- t(seqtab.nochim) %>% as.data.frame()
rownames(asv_tab) <- sub(">", "", asv_headers)
colnames(asv_tab) <- sample.names
asv_tab <- mutate(asv_tab, Seqs = all_of(colnames(seqtab.nochim)), .before = "OSD002")
write.csv2(asv_tab, file = "/Documents/GitHub/CORE/Camilo/Global/OSDV9/ASV_counts_OSDV9.csv")
```

### END ###