---
title: "ASV_Analisis_Regional"

output: html_document
---


## Biblioteca de funciones
```{r libraries, echo=TRUE, message=TRUE, include=FALSE}
library(tidyverse)
library(leaflet)
library(data.table)
library(vegan)
library(treemap)
library(d3treeR)
library(UpSetR)
library(RColorBrewer)
library(plotly)
library(Biostrings)
library(DECIPHER)
library(dendextend)
library(heatmaply)
library(htmlwidgets)
```


## Importe de datos
```{r dataframes, echo=TRUE, message=TRUE, warning=TRUE, include=TRUE}
#Tabla abundancia de ASV
CORE <- read.csv("D:/Documents/GitHub/CORE/DADA2_Regional/seqtab_nonchim.csv", 
                 header = TRUE, 
                 sep = ";", 
                 skip = 0, 
                 fill = TRUE, 
                 row.names = 1)
CORE <- apply(CORE, 2, function(x) as.numeric(as.integer(x))) %>% as.data.frame()
samples <- c("C1A17", "C1F18", "C1A18", "C2A17", "C2F18", "C2A18", "C3A17", "C3F18", "C3A18", "C4A17", "C4F18", "C4A18", "F1A17", "F1F18", "F1A18", "F2A17", "F2F18", "F2A18", "F3A17", "F3F18", "F3A18", "F4A17", "F4F18", "F4A18", "H1A17", "H1F18", "H1A18", "H2A17", "H2F18", "H2A18", "H3A17", "H3F18", "H3A18", "H4A17", "H4F18", "H4A18", "P1F18", "P1A18", "P2F18", "P3F18", "P4F18", "Q1A17", "Q1F18", "Q2A17", "Q2F18", "Q3A17", "Q3F18", "Q3A18", "Q4A17", "Q4F18", "Q4A18", "L1A17", "L1F18", "L1A18", "L2A17", "L2F18", "L2A18", "L3A17", "L3F18", "L3A18", "L4A17", "L4F18", "L4A18")
rownames(CORE) <- samples
write.csv2(CORE, "CORE_ASV.csv")

TAXA <- read.csv("D:/Documents/GitHub/CORE/DADA2_Regional/taxa.csv", 
                 header = TRUE, 
                 sep = ";", 
                 skip = 0) %>% 
  dplyr::rename(Seq = X) %>% 
  add_column(ASV = c(paste0("ASV_", 1:6191)), .after = "Seq")
rownames(TAXA) <- TAXA[, 1]
write.csv2(TAXA, "TAXA.csv")
print(all(colnames(CORE)%in%rownames(TAXA)))
```

## Seleccion de ASV
```{r selection, echo=TRUE, message=TRUE, warning=TRUE}
#Lo primero es filtrar las ASV que no pudieron ser asignadas a nivel de Reino y Supergrupo
non.assigned <- TAXA[rowSums(is.na(TAXA[, c(3,4)])) > 0, ]
NASeq <- non.assigned[,1]
sTAXA <- TAXA[!(row.names(TAXA) %in% all_of(NASeq)), ]
write.csv2(sTAXA, "selected_TAXA.csv")
sCORE <- select(CORE, -all_of(NASeq))
print(all(colnames(sCORE)%in%rownames(sTAXA)))
write.csv2(sCORE, "selected_CORE_ASV.csv")
```


## Union de tablas
```{r union, echo=TRUE, message=TRUE, warning=TRUE}
Union <- as.data.frame(t(sCORE))
Union <- mutate(Union, Seq = all_of(rownames(Union)), .before = "C1A17")
Union <- mutate(Union, 
                Cha = rowSums(Union[2:13]), 
                Fla = rowSums(Union[14:25]), 
                Hu = rowSums(Union[26:37]), 
                Pc = rowSums(Union[38:42]), 
                Qin = rowSums(Union[43:52]), 
                LC = rowSums(Union[53:64]),
                Total = rowSums(Union[2:64])
                )
ATs <- inner_join(Union, sTAXA, by = "Seq") %>% relocate(ASV, .after = Seq)
rownames(ATs) <- all_of(ATs[,1])
write.csv2(ATs, "AT_sCORE.csv")
```


## Preparacion UpSet
```{r preparation, echo=TRUE, message=TRUE, warning=TRUE}
asv <- ATs[, 2]
edited <- ATs[, -c(2, 72:80)]
rownames(edited) <- asv
write.csv2(edited, "edited_AT.csv")
APATs <- edited[, -1]
APATs <- decostand(APATs, method = "pa")
APATs <- add_column(APATs, Seq = all_of(edited$Seq), .before = "C1A17")
write.csv2(APATs, "Ausencia_Presencia_sCORE.csv")
```


## UpSet para "todas" las ASV
```{r complete, echo=TRUE, message=TRUE, warning=TRUE}
aus.pres <- read.csv("Ausencia_Presencia_sCORE.csv", 
                     header = TRUE, 
                     sep = ";", 
                     dec = ".", 
                     skip = 0)

png("Complete_UpSet_All_ASV.png", width = 50, height = 18, units = "in", res = 600)
upset(aus.pres, 
      nsets = 9, 
      nintersects = NA, 
      sets = c("Cha", "Fla", "Hu", "Pc", "LC", "Qin"), 
      empty.intersections = "on",
      point.size = 3.5, 
      line.size = 1.5, 
      text.scale = 2, 
      mainbar.y.label = "Sites intersections", 
      sets.x.label = "ASV per sampling site"
      )
dev.off()

png("Selected_UpSet.png", width = 30, height = 15, units = "in", res = 600)
upset(aus.pres, 
      nsets = 6, 
      nintersects = NA, 
      sets = c("Cha", "Fla", "Hu", "Pc", "LC", "Qin"), 
      intersections = list("Qin", "LC", "Pc", "Hu", "Fla", "Cha", 
                           list("Cha", "Fla"), 
                           list("Hu", "Pc"), 
                           list("Qin", "LC"), 
                           list("Cha", "Hu"), 
                           list("Cha", "Qin"), 
                           list("Hu", "Qin"), 
                           list("Fla", "Pc"), 
                           list("Fla", "LC"), 
                           list("Pc", "LC"), 
                           list("Cha", "Hu", "Qin"), 
                           list("Fla", "Pc", "LC"), 
                           list("Cha", "Fla", "Qin", "LC"), 
                           list("Hu", "Pc", "Qin", "LC"), 
                           list("Cha", "Fla", "Hu", "Pc"), 
                           list("Cha", "Fla", "Hu", "Pc", "LC"), 
                           list("Cha", "Fla", "Hu", "Pc", "Qin"), 
                           list("Cha", "Fla", "Hu", "Pc", "LC", "Qin")
                           ),
      empty.intersections = "on",
      keep.order = TRUE, 
      query.legend = "top", 
      queries = list(list(query = intersects, params = "Cha", color = "#FF9F1C", active = TRUE, query.name = "Unique Chañaral ASV"), 
                     list(query = intersects, params = "Fla", color = "#FFCA85", active = TRUE, query.name = "Unique Flamenco ASV"), 
                     list(query = intersects, params = "Hu", color = "#2EC4B6", active = TRUE, query.name = "Unique Huasco ASV"), 
                     list(query = intersects, params = "Pc", color = "#CBF3F0", active = TRUE, query.name = "Unique Punta Choros ASV"), 
                     list(query = intersects, params = "LC", color = "#DEB1FB", active = TRUE, query.name = "Unique Las Cruces ASV"), 
                     list(query = intersects, params = "Qin", color = "#AC3CF6", active = TRUE, query.name = "Unique Quintero ASV"), 
                     list(query = intersects, params = list("Cha", "Fla", "Hu", "Pc"), color = "#0466C8", active = TRUE, query.name = "Metal axis shared ASV"), 
                     list(query = intersects, params = list("Cha", "Fla", "Hu", "Pc", "LC", "Qin"), color = "#F94144", active = TRUE, query.name = "Total shared ASV")
                     ), 
      point.size = 3.5, 
      line.size = 1.5, 
      text.scale = 2, 
      mainbar.y.label = "Sites intersections", 
      sets.x.label = "ASV per sampling site")
dev.off()
```


## Agrupar ASV por clasificacion taxonomica
```{r clustering, echo=TRUE, message=TRUE, warning=TRUE}
#Esta es la funcion que dejo el Benja en el github del lab
Tax.sum <- function(OTU.Table, Tax.Table, Tax.lvl ){
  z <- NULL
  y <- NULL
  for (i in 1:length(unique(Tax.Table[colnames(OTU.Table),Tax.lvl]))) {
    if (length(OTU.Table[,which(Tax.Table[colnames(OTU.Table),Tax.lvl]==unique(Tax.Table[colnames(OTU.Table),Tax.lvl])[i])])!=length(rownames(OTU.Table))) {
      z <- which(Tax.Table[colnames(OTU.Table),Tax.lvl]==unique(Tax.Table[colnames(OTU.Table),Tax.lvl])[i])
      y <- cbind(y, apply(OTU.Table[,which(Tax.Table[colnames(OTU.Table),Tax.lvl]==unique(Tax.Table[colnames(OTU.Table),Tax.lvl])[i])], 1, function(x) sum(x)))
    } else { 
      y <- cbind(y, OTU.Table[,which(Tax.Table[colnames(OTU.Table),Tax.lvl]==unique(Tax.Table[colnames(OTU.Table),Tax.lvl])[i])])
    }
  }
  colnames(y) <- unique(Tax.Table[colnames(OTU.Table),Tax.lvl])
  invisible((y))
}

Phylum <- Tax.sum(sCORE, sTAXA, 5) %>% 
  t() %>% 
  as.data.frame() %>% 
  mutate(Color = c("#440154", "#4E0066", "#007F5F", "#359548", "#20A387", "#FFBE17", "#6AAB30", "#1C3B74", "#83E377", "#BACC0C", "#FA8072", "#F97100", "#FFBE17", "#F94144", "#FA776B", "#95D840", "#F8417D", "#F95C74", "#ACDD3C", "#FB9C70", "#C5DBEA", "#000000", "#8BB7D4", "#5193BE", "#00609F", "#AA006A", "#023E8A", "#0B0B30", "#000078", "#9B2226", "#161664", "#FF0000", "#17315F", "#CC0000", "#4E1114", "#DEB1FB"))
write.csv2(Phylum, "phylum_color_CORE.csv")
Phylum.Total <- mutate(Phylum,
                 Cha = rowSums(Phylum[1:12]), 
                 Fla = rowSums(Phylum[13:24]), 
                 Hu = rowSums(Phylum[25:36]), 
                 Pc = rowSums(Phylum[37:41]), 
                 Qin = rowSums(Phylum[42:51]), 
                 LC = rowSums(Phylum[52:63]), 
                 Total = rowSums(Phylum[1:63]), 
                 .after = "L4A18") %>% 
  as.data.frame()
write.csv2(Phylum.Total, "phylum_color_total_CORE.csv")

png("Contribution_Distribution_Phylum_Total_ASV.png", width = 17, height = 15, units = 'in', res = 600)
treemap(read.csv("phylum_color_total_CORE.csv", 
                 header = TRUE, 
                 sep = ";", 
                 dec = ".", 
                 skip = 0), 
        index = "X", 
        vSize = "Total", 
        type = "color",
        vColor = "Color", 
        position.legend = "none", 
        fontsize.labels = 20,
        fontsize.title = 30,
        title = "Distribution and contribution of total ASV",
        title.legend = NA,
        border.col = NA
)
dev.off()

png("Treemap_Phylum_Total_Legend.png", width = 10, height = 7, units = 'in', res = 600)
plot.new()
par(mar = c(0,0,0,0), oma = c(0,0,0,0))
legend("center", 
       legend = read.csv("phylum_color_total_CORE.csv", 
                         header = TRUE, 
                         sep = ";", 
                         dec = ".", 
                         skip = 0)[,1], 
       cex = 1.2, 
       ncol = 1, 
       fill = Phylum.Total$Color, 
       x.intersp = 0.3, 
       xjust = 0.3, 
       yjust = 0.5, 
       y.intersp = 1, 
       bty = "n", 
       adj = 0, 
       text.width = 0.3, 
       pt.cex = 0.3)
dev.off()

#Sólo PPE
PhyPPE <- read.csv("phylum_color_total_CORE.csv", 
                   header = TRUE, 
                   sep = ";", 
                   dec = ".", 
                   skip = 0, 
                   fill = TRUE)
PhyPPE <- PhyPPE[c(1,5,6,8,13,14,16),]

png("Contribution_Distribution_Phylum_PPE_ASV.png", width = 17, height = 15, units = 'in', res = 600)
treemap(PhyPPE, 
        index = "X", 
        vSize = "Total", 
        type = "color",
        vColor = "Color", 
        position.legend = "none", 
        fontsize.labels = 20,
        fontsize.title = 30,
        title = "Distribution and contribution of PPE ASV",
        title.legend = NA,
        border.col = NA
)
dev.off()
```


```{r upset ppe, echo=TRUE,message=TRUE,warning=TRUE}
#UpSet para PPE
ppe.taxa <- filter(sTAXA, Division == "Chlorophyta" | Division == "Ochrophyta" | Division == "Cryptophyta" | Division == "Haptophyta" | Division == "Katablepharidophyta" | Division == "Rhodophyta" | Division == "Cryptophyta:nucl")
ppe.asv <- select(sCORE, all_of(ppe.taxa$Seq))
ppe.auspres <- filter(aus.pres, Seq %in% all_of(ppe.taxa$Seq))
ppe.div <- Tax.sum(ppe.asv, ppe.taxa, 5) %>% as.data.frame()
colnames(ppe.div)[c(3,5)] <- c("A", "B")
ppe.div <- mutate(ppe.div, Cryptophyta = rowSums(ppe.div[c(3,5)])) %>% 
  select(Chlorophyta, Ochrophyta, Cryptophyta, Haptophyta, Katablepharidophyta, Rhodophyta)

png("Selected_PPE_UpSet.png", width = 30, height = 15, units = "in", res = 600)
upset(ppe.auspres, 
      nsets = 6, 
      nintersects = NA, 
      sets = c("Cha", "Fla", "Hu", "Pc", "LC", "Qin"), 
      intersections = list("Qin", "LC", "Pc", "Hu", "Fla", "Cha", 
                           list("Cha", "Fla"), 
                           list("Hu", "Pc"), 
                           list("Qin", "LC"), 
                           list("Cha", "Hu"), 
                           list("Cha", "Qin"), 
                           list("Hu", "Qin"), 
                           list("Fla", "Pc"), 
                           list("Fla", "LC"), 
                           list("Pc", "LC"), 
                           list("Cha", "Hu", "Qin"), 
                           list("Fla", "Pc", "LC"), 
                           list("Cha", "Fla", "Qin", "LC"), 
                           list("Hu", "Pc", "Qin", "LC"), 
                           list("Cha", "Fla", "Hu", "Pc"), 
                           list("Cha", "Fla", "Hu", "Pc", "LC"), 
                           list("Cha", "Fla", "Hu", "Pc", "Qin"), 
                           list("Cha", "Fla", "Hu", "Pc", "LC", "Qin")
                           ),
      empty.intersections = "on",
      keep.order = TRUE, 
      query.legend = "top", 
      queries = list(list(query = intersects, params = "Cha", color = "#FF9F1C", active = TRUE, query.name = "Unique Chañaral ASV"), 
                     list(query = intersects, params = "Fla", color = "#FFCA85", active = TRUE, query.name = "Unique Flamenco ASV"), 
                     list(query = intersects, params = "Hu", color = "#2EC4B6", active = TRUE, query.name = "Unique Huasco ASV"), 
                     list(query = intersects, params = "Pc", color = "#CBF3F0", active = TRUE, query.name = "Unique Punta Choros ASV"), 
                     list(query = intersects, params = "LC", color = "#DEB1FB", active = TRUE, query.name = "Unique Las Cruces ASV"), 
                     list(query = intersects, params = "Qin", color = "#AC3CF6", active = TRUE, query.name = "Unique Quintero ASV"), 
                     list(query = intersects, params = list("Cha", "Fla", "Hu", "Pc"), color = "#0466C8", active = TRUE, query.name = "Metal axis shared ASV"), 
                     list(query = intersects, params = list("Cha", "Fla", "Hu", "Pc", "LC", "Qin"), color = "#F94144", active = TRUE, query.name = "Total shared ASV")
                     ), 
      point.size = 3.5, 
      line.size = 1.5, 
      text.scale = 2, 
      mainbar.y.label = "Sites intersections", 
      sets.x.label = "ASV per sampling site")
dev.off()

png("Selected_PPE_UpSet_2.png", width = 30, height = 15, units = "in", res = 300)
upset(ppe.auspres, 
      nsets = 6, 
      nintersects = NA, 
      sets = c("Cha", "Fla", "Hu", "Pc", "LC", "Qin"), 
      intersections = list("Qin", "LC", "Pc", "Hu", "Fla", "Cha", 
                           list("Cha", "Fla"), 
                           list("Hu", "Pc"), 
                           list("Qin", "LC"), 
                           list("Cha", "Hu"), 
                           list("Cha", "Qin"), 
                           list("Hu", "Qin"), 
                           list("Fla", "Pc"), 
                           list("Fla", "LC"), 
                           list("Pc", "LC"), 
                           list("Cha", "Hu", "Qin"), 
                           list("Fla", "Pc", "LC"), 
                           list("Cha", "Fla", "Qin", "LC"), 
                           list("Hu", "Pc", "Qin", "LC"), 
                           list("Cha", "Fla", "Hu", "Pc"), 
                           list("Cha", "Fla", "Hu", "Pc", "LC"), 
                           list("Cha", "Fla", "Hu", "Pc", "Qin"), 
                           list("Cha", "Fla", "Hu", "Pc", "LC", "Qin")
                           ),
      empty.intersections = "on",
      keep.order = TRUE, 
      query.legend = "top", 
      queries = list(list(query = intersects, params = "Cha", color = "#FF9F1C", active = TRUE, query.name = "Unique Chañaral ASV"), 
                     list(query = intersects, params = "Fla", color = "#FFCA85", active = TRUE, query.name = "Unique Flamenco ASV"), 
                     list(query = intersects, params = "Hu", color = "#2EC4B6", active = TRUE, query.name = "Unique Huasco ASV"), 
                     list(query = intersects, params = "Pc", color = "#CBF3F0", active = TRUE, query.name = "Unique Punta Choros ASV"), 
                     list(query = intersects, params = "LC", color = "#DEB1FB", active = TRUE, query.name = "Unique Las Cruces ASV"), 
                     list(query = intersects, params = "Qin", color = "#AC3CF6", active = TRUE, query.name = "Unique Quintero ASV"), 
                     list(query = intersects, params = list("Cha", "Fla", "Hu", "Pc"), color = "#0466C8", active = TRUE, query.name = "Metal axis shared ASV"), 
                     list(query = intersects, params = list("Cha", "Fla", "Hu", "Pc", "LC", "Qin"), color = "#F94144", active = TRUE, query.name = "Total shared ASV")
                     ), 
      point.size = 3.5, 
      line.size = 1.5, 
      text.scale = 2, 
      mainbar.y.label = "Sites intersections", 
      sets.x.label = "ASV per sampling site")
dev.off()
```


```{r recognition, echo=TRUE, message=TRUE, warning=TRUE}
shared <- ppe.auspres %>% filter(Cha == 1 & Fla == 1 & Hu == 1 & Pc == 1 & Qin == 1 & LC == 1)
shared.abundance <- select(ppe.asv, all_of(shared$Seq))
#Para Lucas
ppe.shared.asv <- shared.abundance
colnames(ppe.shared.asv) <- shared$X
write.csv2(ppe.shared.asv, "/Users/Artemis/Documents/GitHub/CORE/Lucas/shared_ppe_asv_abundance.csv")
shared.division <- Tax.sum(shared.abundance, ppe.taxa, 5) %>% as.data.frame()
colnames(shared.division)[c(3,5)] <- c("A", "B")
shared.division <- mutate(shared.division, Cryptophyta = rowSums(shared.division[c(3,5)])) %>% 
  select(Chlorophyta, Ochrophyta, Cryptophyta, Haptophyta, Katablepharidophyta)
write.csv2(shared.division, "ppe_shared_division_abundance.csv")
ppe.wo.shared <- select(ppe.asv, -all_of(shared$Seq))
woshared.division <- Tax.sum(ppe.wo.shared, ppe.taxa, 5) %>% as.data.frame()
colnames(woshared.division)[c(3,6)] <- c("A", "B")
woshared.division <- mutate(woshared.division, 
                            Cryptophyta = rowSums(woshared.division[c(3,6)])) %>% 
  select(Chlorophyta, Ochrophyta, Cryptophyta, Haptophyta, Katablepharidophyta, Rhodophyta)
write.csv2(woshared.division, file = "ppe_not_shared_division_abundance.csv")

chañaral <- ppe.auspres %>% filter(Cha == 1)
ppe.asv.cha <- select(ppe.asv, all_of(chañaral$Seq))
colnames(ppe.asv.cha) <- chañaral$X
ppe.asv.cha <- ppe.asv.cha[c(1:12),]
write.csv2(ppe.asv.cha, "/Users/Artemis/Documents/GitHub/CORE/Lucas/chanaral_ppe_asv_abundance.csv")
unique.chañaral <- chañaral %>% filter(Fla == 0 & Hu == 0 & Pc == 0 & Qin == 0 & LC == 0)
unique.cha.abun <- select(ppe.asv, all_of(unique.chañaral$Seq))
ucha.abun <- unique.cha.abun
colnames(ucha.abun) <- unique.chañaral$X
ucha.abun <- ucha.abun[c(1:12),]
write.csv2(ucha.abun, "/Users/Artemis/Documents/GitHub/CORE/Lucas/unique_chanaral_ppe_asv_abundance.csv")
chañaral.division <- Tax.sum(unique.cha.abun, ppe.taxa, 5) %>% as.data.frame()
chañaral.division <- chañaral.division[, c(2,1,3,4)]
write.csv2(chañaral.division, file = "unique_chanaral_ppe_asv_division_abundance.csv")
ppe.without.us <- select(ppe.wo.shared, -all_of(unique.chañaral$Seq))
#wous.division al final

flamenco <- ppe.auspres %>% filter(Fla == 1)
ppe.asv.fla <- select(ppe.asv, all_of(flamenco$Seq))
colnames(ppe.asv.fla) <- flamenco$X
ppe.asv.fla <- ppe.asv.fla[c(13:24),]
write.csv2(ppe.asv.fla, "/Users/Artemis/Documents/GitHub/CORE/Lucas/flamenco_ppe_asv_abundance.csv")
unique.flamenco <- flamenco %>% filter(Cha == 0 & Hu == 0 & Pc == 0 & Qin == 0 & LC == 0)
unique.fla.abun <- select(ppe.asv, all_of(unique.flamenco$Seq))
ufla.abun <- unique.fla.abun
colnames(ufla.abun) <- unique.flamenco$X
ufla.abun <- ufla.abun[c(13:24),]
write.csv2(ufla.abun, "/Users/Artemis/Documents/GitHub/CORE/Lucas/unique_flamenco_ppe_asv_abundance.csv")
flamenco.division <- Tax.sum(unique.fla.abun, ppe.taxa, 5) %>% as.data.frame()
colnames(flamenco.division)[3] <- "Cryptophyta"
flamenco.division <- flamenco.division[c(13:24), c(4,2,3,1,5,6)]
write.csv2(flamenco.division, "unique_flamenco_ppe_asv_division_abundance.csv")
ppe.without.us <- select(ppe.without.us, -all_of(unique.flamenco$Seq))

huasco <- ppe.auspres %>% filter(Hu == 1)
ppe.asv.hu <- select(ppe.asv, all_of(huasco$Seq))
colnames(ppe.asv.hu) <- huasco$X
ppe.asv.hu <- ppe.asv.hu[c(25:36),]
write.csv2(ppe.asv.hu, "/Users/Artemis/Documents/GitHub/CORE/Lucas/huasco_ppe_asv_abundance.csv")
unique.huasco <- huasco %>% filter(Cha == 0 & Fla == 0 & Pc == 0 & Qin == 0 & LC == 0)
unique.hu.abun <- select(ppe.asv, all_of(unique.huasco$Seq))
uhu.abun <- unique.hu.abun
colnames(uhu.abun) <- unique.huasco$X
uhu.abun <- uhu.abun[c(25:36),]
write.csv2(uhu.abun, "/Users/Artemis/Documents/GitHub/CORE/Lucas/unique_huasco_ppe_asv_abundance.csv")
huasco.division <- Tax.sum(unique.hu.abun, ppe.taxa, 5) %>% as.data.frame()
colnames(huasco.division)[5] <- "Cryptophyta"
huasco.division <- huasco.division[c(25:36), c(1,2,5,4,3)]
write.csv2(huasco.division, "unique_huasco_ppe_asv_division_abundance.csv")
ppe.without.us <- select(ppe.without.us, -all_of(unique.huasco$Seq))

ptachoros <- ppe.auspres %>% filter(Pc == 1)
ppe.asv.pc <- select(ppe.asv, all_of(ptachoros$Seq))
colnames(ppe.asv.pc) <- ptachoros$X
ppe.asv.pc <- ppe.asv.pc[c(37:41),]
write.csv2(ppe.asv.pc, "/Users/Artemis/Documents/GitHub/CORE/Lucas/punta_choros_ppe_asv_abundance.csv")
unique.ptachoros <- ptachoros %>% filter(Cha == 0 & Fla == 0 & Hu == 0 & Qin == 0 & LC == 0)
unique.pc.abun <- select(ppe.asv, all_of(unique.ptachoros$Seq))
upc.abun <- unique.pc.abun
colnames(upc.abun) <- unique.ptachoros$X
upc.abun <- upc.abun[c(37:41),]
write.csv2(uhu.abun, "/Users/Artemis/Documents/GitHub/CORE/Lucas/unique_punta_choros_ppe_asv_abundance.csv")
ptachoros.division <- Tax.sum(unique.pc.abun, ppe.taxa, 5) %>% as.data.frame()
ptachoros.division <- ptachoros.division[c(37:41), c(4,1,5,3,2)]
write.csv2(ptachoros.division, "unique_punta_choros_ppe_asv_division_abundance.csv")
ppe.without.us <- select(ppe.without.us, -all_of(unique.ptachoros$Seq))

quintero <- ppe.auspres %>% filter(Qin == 1)
ppe.asv.qin <- select(ppe.asv, all_of(quintero$Seq))
colnames(ppe.asv.qin) <- quintero$X
ppe.asv.qin <- ppe.asv.qin[c(42:51),]
write.csv2(ppe.asv.qin, "/Users/Artemis/Documents/GitHub/CORE/Lucas/quintero_ppe_asv_abundance.csv")
unique.quintero <- quintero %>% filter(Cha == 0 & Fla == 0 & Hu == 0 & Pc == 0 & LC == 0)
unique.qin.abun <- select(ppe.asv, all_of(unique.quintero$Seq))
uqin.abun <- unique.qin.abun
colnames(uqin.abun) <- unique.quintero$X
uqin.abun <- uqin.abun[c(42:51),]
write.csv2(uhu.abun, "/Users/Artemis/Documents/GitHub/CORE/Lucas/unique_quintero_ppe_asv_abundance.csv")
quintero.division <- Tax.sum(unique.qin.abun, ppe.taxa, 5) %>% as.data.frame()
quintero.division <- quintero.division[c(42:51), c(3,1,6,4,5,2)]
write.csv2(quintero.division, "unique_quintero_ppe_asv_division_abundance.csv")
ppe.without.us <- select(ppe.without.us, -all_of(unique.quintero$Seq))

lascruces <- ppe.auspres %>% filter(LC == 1)
ppe.asv.lc <- select(ppe.asv, all_of(lascruces$Seq))
colnames(ppe.asv.lc) <- lascruces$X
ppe.asv.lc <- ppe.asv.lc[c(52:63),]
write.csv2(ppe.asv.lc, "/Users/Artemis/Documents/GitHub/CORE/Lucas/las_cruces_ppe_asv_abundance.csv")
unique.lascruces <- lascruces %>% filter(Cha == 0 & Fla == 0 & Hu == 0 & Pc == 0 & Qin == 0)
unique.lc.abun <- select(ppe.asv, all_of(unique.lascruces$Seq))
ulc.abun <- unique.lc.abun
colnames(ulc.abun) <- unique.lascruces$X
ulc.abun <- ulc.abun[c(52:63),]
write.csv2(ulc.abun, "/Users/Artemis/Documents/GitHub/CORE/Lucas/unique_las_cruces_ppe_asv_abundance.csv")
lascruces.division <- Tax.sum(unique.lc.abun, ppe.taxa, 5) %>% as.data.frame()
colnames(lascruces.division)[c(5,6)] <- c("A", "B")
lascruces.division <- mutate(lascruces.division, 
                             Cryptophyta = rowSums(lascruces.division[c(5,6)]))
lascruces.division <- lascruces.division[c(52:63), c(3,2,8,7,4,1)]
write.csv2(lascruces.division, "unique_las_cruces_ppe_asv_division_abundance.csv")
ppe.without.us <- select(ppe.without.us, -all_of(unique.lascruces$Seq))
wous.division <- Tax.sum(ppe.without.us, ppe.taxa, 5) %>% as.data.frame()
colnames(wous.division)[c(3,6)] <- c("A","B")
wous.division <- mutate(wous.division, 
                        Cryptophyta = rowSums(wous.division[c(3,6)]))
wous.division <- wous.division[, c(2,1,8,7,5,4)]
write.csv2(wous.division, "other_ppe_asv_division_abundance.csv")

pPPETot <- Phylum.Total[c(1,5,6,13,8,14,16), -c(64:71)]
pPPETot <- as.data.frame(t(pPPETot))
colnames(pPPETot)[c(3,4)] <- c("A", "B")
pPPETot <- mutate(pPPETot, Cryptophyta = rowSums(pPPETot[c(3,4)])) %>% select(Chlorophyta, Ochrophyta, Cryptophyta, Haptophyta, Katablepharidophyta, Rhodophyta)
write.csv2(pPPETot, "ppe_total_division_abundance.csv")

#Proximo dataframe editado externamente
div.unique <- read.csv2("ppe_unique_division_abundance.csv", 
                        header = TRUE, 
                        sep = ";", 
                        dec = ".", 
                        row.names = 1, 
                        fill = TRUE, 
                        skip = 0)

ppe.diff <- read.csv2("other_ppe_asv_division_abundance.csv", 
                      header = TRUE, 
                      sep = ";", 
                      dec = ".", 
                      row.names = 1, 
                      skip = 0, 
                      fill = TRUE)

div.comp <- read.csv2("composite_ppe_asv_division_abundance.csv", 
                      header = TRUE,
                      sep = ";", 
                      dec = ".", 
                      skip = 0, 
                      fill = TRUE,
                      row.names = 1)
div.comp <- div.comp %>% 
  mutate(Shared = rowSums(div.comp[c(7:12)]), 
         Unique = rowSums(div.comp[c(13:18)]), 
         Rest = rowSums(div.comp[c(19:24)])
         )
macro.div.comp <- div.comp[, c(25:27)]
macro.div.comp <- as.data.frame(t(macro.div.comp))
macro.col <- mutate(macro.div.comp, 
                    Colors = c("#2F3E46", 
                               "#F93822", 
                               "#CED4DA")
                    )
write.csv2(macro.col, "macro_color_PPE_CORE.csv")

micro.div.comp <- div.comp[, -c(1:6, 13:25)]
colnames(micro.div.comp) <- c("Chlorophyta", "Ochrophyta", "Cryptophyta", "Haptophyta", "Katablepharidophyta", "Rhodophyta", "Unique", "Rest")
micro.div.comp <- as.data.frame(t(micro.div.comp))
micro.col <- mutate(micro.div.comp, 
                    Colors = c("#440154", 
                               "#20A387", 
                               "#FFBE17", 
                               "#1C3B74", 
                               "#9EF01A", 
                               "#95D840", 
                               "#FFBE17", 
                               "#CED4DA")
                    )

micro.col <- mutate(micro.div.comp, 
                    Colors = c("#002C3D", 
                               "#FCA72D", 
                               "#BACC0C", 
                               "#16DB93", 
                               "#F1F500", 
                               "#00564E", 
                               "#F93822", 
                               "#CED4DA")
                    )
write.csv2(micro.col, "detailed_phylum_color_PPE_ASV_CORE.csv")

mid.div.comp <- div.comp[-c(1:6, 13:25, 27)]
colnames(mid.div.comp) <- c("Chlorophyta", "Ochrophyta", "Cryptophyta", "Haptophyta", "Katablepharidophyta", "Rhodophyta", "Unique")
mid.div.comp <- as.data.frame(t(mid.div.comp))
mid.col <- mutate(mid.div.comp, 
                  Colors = c("#002C3D", 
                             "#FCA72D", 
                             "#BACC0C", 
                             "#16DB93", 
                             "#F1F500", 
                             "#00564E", 
                             "#F93822")
                  )
```


```{r relative, echo=TRUE, message=TRUE,warning=TRUE}
rltv.Otu.Table <- function(x){
  x.Data.rltv <- NULL
  for (i in 1:dim(x)[1]) {
    x.Data.rltv <- rbind(x.Data.rltv, x[i,]/apply(x, 1, function(x) sum(x))[i])
  }
  rownames(x.Data.rltv) <- rownames(x)
  invisible(x.Data.rltv)
}

relative.macro <- rltv.Otu.Table(t(macro.div.comp))
apply(relative.macro, 1, function(x) sum(x))[1:63]

png("Relative_Abundance_Macro_Composite_PPE_ASV.png", width = 20, height = 11, units = 'in', res = 600)
par(mar = c(5.1,4.1,4.1,2.1), oma = c(0,0,0,0))
barplot(t(relative.macro), 
        border = NA, 
        ylab = "Relative Abundance", 
        ylim = c(0,1), 
        axes = TRUE, 
        col = macro.col$Colors, 
        las = 2, 
        cex.names = 0.8, 
        cex.axis = 0.9)
dev.off()

png("Relative_Abundance_Macro_Composite_PPE_ASV_2.png", width = 20, height = 11, units = 'in', res = 300)
par(mar = c(5.1,4.1,4.1,2.1), oma = c(0,0,0,0))
barplot(t(relative.macro), 
        border = NA, 
        ylab = "Relative Abundance", 
        ylim = c(0,1), 
        axes = TRUE, 
        col = macro.col$Colors, 
        las = 2, 
        cex.names = 0.8, 
        cex.axis = 0.9)
dev.off()

png("Relative_Abundance_Macro_Composite_PPE_ASV_Legend.png", width = 3, height = 5, units = 'in', res = 600)
plot.new()
par(mar = c(0,0,0,0), oma = c(0,0,0,0))
legend("center", legend = colnames(relative.macro), cex = 1, ncol = 1, fill = macro.col$Colors, x.intersp = 0.1, xjust = 0.1, yjust = 0.3, y.intersp = 1.2, bty = "n", adj = 0, text.width = 0.1, pt.cex = 0.1)
dev.off()

relative.micro <- rltv.Otu.Table(t(micro.div.comp))
apply(relative.macro, 1, function(x) sum(x))[1:63]

png("Relative_Abundance_Detailed_Shared_Composite_PPE_ASV.png", width = 20, height = 11, units = 'in', res = 600)
par(mar = c(5.1,4.1,4.1,2.1), oma = c(0,0,0,0))
barplot(t(relative.micro), 
        border = NA, 
        ylab = "Relative Abundance", 
        ylim = c(0,1), 
        axes = TRUE, 
        col = micro.col$Colors, 
        las = 2, 
        cex.names = 0.8, 
        cex.axis = 0.9)
dev.off()

png("Relative_Abundance_Detailed_Shared_Composite_PPE_ASV_2.png", width = 20, height = 11, units = 'in', res = 300)
par(mar = c(5.1,4.1,4.1,2.1), oma = c(0,0,0,0))
barplot(t(relative.micro), 
        border = NA, 
        ylab = "Relative Abundance", 
        ylim = c(0,1), 
        axes = TRUE, 
        col = micro.col$Colors, 
        las = 2, 
        cex.names = 0.8, 
        cex.axis = 0.9)
dev.off()

relative.mid <- rltv.Otu.Table(t(mid.div.comp))
apply(relative.mid, 1, function(x) sum(x))[1:63]

png("Relative_Abundance_Mid_Detailed_Shared_Composite_PPE_ASV_2.png", width = 20, height = 11, units = 'in', res = 300)
par(mar = c(5.1,4.1,4.1,2.1), oma = c(0,0,0,0))
barplot(t(relative.mid), 
        border = NA, 
        ylab = "Relative Abundance", 
        ylim = c(0,1), 
        axes = TRUE, 
        col = mid.col$Colors, 
        las = 2, 
        cex.names = 0.8, 
        cex.axis = 0.9)
dev.off()

png("Relative_Abundance_Detailed_Shared_Composite_PPE_ASV_Legend.png", width = 5, height = 5, units = 'in', res = 300)
plot.new()
par(mar = c(0,0,0,0), oma = c(0,0,0,0))
legend("center", legend = colnames(relative.micro), cex = 1, ncol = 1, fill = micro.col$Colors, x.intersp = 0.1, xjust = 0.1, yjust = 0.3, y.intersp = 1.2, bty = "n", adj = 0, text.width = 0.1, pt.cex = 0.1)
dev.off()

ppe.rltv <- Phylum.Total[c(1,5,6,13,8,14,16), -c(64:70)]
relative.ppe <- as.data.frame(t(ppe.rltv[,-64]))
colnames(relative.ppe)[c(3,7)] <- c("A", "B")
relative.ppe <- mutate(relative.ppe, 
                       Cryptophyta = rowSums(relative.ppe[c(3,7)]),
                       .after = "Ochrophyta")
relative.ppe <- relative.ppe[, -c(4,8)]
relative.ppe <- rltv.Otu.Table(relative.ppe)
apply(relative.ppe, 1, function(x) sum(x))[1:63]
  
png("Relative_Abundance_Phylum_PPE_ASV.png", width = 20, height = 11, units = 'in', res = 600)
par(mar = c(5.1,4.1,4.1,2.1), oma = c(0,0,0,0))
barplot(t(relative.ppe), 
        border = NA, 
        ylab = "Relative Abundance", 
        ylim = c(0,1), 
        axes = TRUE, 
        col = ppe.rltv[-7,]$Color, 
        las = 2, 
        cex.names = 0.8, 
        cex.axis = 0.9)
dev.off()

png("Relative_Abundance_Phylum_PPE_ASV_Legend.png", width = 5, height = 7, units = 'in', res = 600)
plot.new()
par(mar = c(0,0,0,0), oma = c(0,0,0,0))
legend("center", legend = colnames(relative.ppe), cex = 1, ncol = 1, fill = ppe.rltv[-7,]$Color, x.intersp = 0.1, xjust = 0.1, yjust = 0.3, y.intersp = 1, bty = "n", adj = 0, text.width = 0.1, pt.cex = 0.1)
dev.off()
```


```{r, echo=TRUE, message=TRUE, warning=TRUE}
#Esto lo voy a arreglar pero por mientras lo dejaré así
ppe.shaseqs <- ppe.auspres %>% filter(Cha == 1 & Fla == 1 & Hu == 1 & Pc == 1 & LC == 1 & Qin == 1)
ppe.shaseqs <- filter(ATs, Seq %in% all_of(ppe.shaseqs$Seq))
ppe.shared.asv <- select(ppe.asv, all_of(ppe.shaseqs$Seq))
nombres <- paste(ppe.shaseqs$ASV, ppe.shaseqs$Species, sep = "_")
colnames(ppe.shared.asv) <- nombres
metal.env <- read.csv2("metal_environment_concentrations.csv", 
                       header = TRUE, 
                       sep = ";", 
                       dec = ".", 
                       skip = 0, 
                       fill = TRUE, 
                       row.names = 1)
metal.env <- metal.env[-c(62:63),]
metal.env$Site <- as.factor(metal.env$Site)
metal.hel <- vegan::decostand(x = ppe.shared.asv, method = "hellinger")
metal.dist <- vegan::vegdist(x = metal.hel, method = "bray", diag = TRUE)
npmanova <- vegan::adonis(metal.dist ~ Site, data = metal.env, permutations = 1000)
npmanova
str(npmanova)
npmanova$aov.tab$`Pr(>F)`[1]
p.adonis <- npmanova[["aov.tab"]][["Pr(>F)"]][1]
p.adonis

otro.modelo <- vegan::adonis(metal.dist ~ Copper*Iron, 
                             data = metal.env, 
                             permutations = 1000)
otro.modelo

#volviendo al modelo anterior
pairwise_p <- numeric()
chafla.dist <- vegan::vegdist(metal.hel[c(1:24),], method = "bray", diag = TRUE)
chafla.env <- metal.env[c(1:24),]
chafla.test <- vegan::adonis(chafla.dist~Site, 
                             data = chafla.env, 
                             permutations = 1000)
pairwise_p["Cha_Fla"] <- chafla.test[["aov.tab"]][["Pr(>F)"]][1]

chahu.dist <- vegan::vegdist(metal.hel[c(1:12,25:36),], method = "bray", diag = TRUE)
chahu.env <- metal.env[c(1:12, 25:36),]
chahu.test <- vegan::adonis(chahu.dist~Site, 
                             data = chahu.env, 
                             permutations = 1000)
pairwise_p["Cha_Hu"] <- chahu.test[["aov.tab"]][["Pr(>F)"]][1]

chapc.dist <- vegan::vegdist(metal.hel[c(1:12, 37:41),], method = "bray", diag = TRUE)
chapc.env <- metal.env[c(1:12, 37:41),]
chapc.test <- vegan::adonis(chapc.dist~Site, 
                             data = chapc.env, 
                             permutations = 1000)
pairwise_p["Cha_Pc"] <- chapc.test[["aov.tab"]][["Pr(>F)"]][1]

chalc.dist <- vegan::vegdist(metal.hel[c(1:12, 42:53),], method = "bray", diag = TRUE)
chalc.env <- metal.env[c(1:12,42:53),]
chalc.test <- vegan::adonis(chalc.dist~Site, 
                             data = chalc.env, 
                             permutations = 1000)
pairwise_p["Cha_LC"] <- chalc.test[["aov.tab"]][["Pr(>F)"]][1]

chaqin.dist <- vegan::vegdist(metal.hel[c(1:12,54:63),], method = "bray", diag = TRUE)
chaqin.env <- metal.env[c(1:12,54:63),]
chaqin.test <- vegan::adonis(chaqin.dist~Site, 
                             data = chaqin.env, 
                             permutations = 1000)
pairwise_p["Cha_Qin"] <- chaqin.test[["aov.tab"]][["Pr(>F)"]][1]

flahu.dist <- vegan::vegdist(metal.hel[c(13:36),], method = "bray", diag = TRUE)
flahu.env <- metal.env[c(13:36),]
flahu.test <- vegan::adonis(flahu.dist~Site, 
                             data = flahu.env, 
                             permutations = 1000)
pairwise_p["Fla_Hu"] <- flahu.test[["aov.tab"]][["Pr(>F)"]][1]

flapc.dist <- vegan::vegdist(metal.hel[c(13:24,37:41),], method = "bray", diag = TRUE)
flapc.env <- metal.env[c(13:24,37:41),]
flapc.test <- vegan::adonis(flapc.dist~Site, 
                             data = flapc.env, 
                             permutations = 1000)
pairwise_p["Fla_Pc"] <- flapc.test[["aov.tab"]][["Pr(>F)"]][1]

flalc.dist <- vegan::vegdist(metal.hel[c(13:24,42:53),], method = "bray", diag = TRUE)
flalc.env <- metal.env[c(13:24,42:53),]
flalc.test <- vegan::adonis(flalc.dist~Site, 
                             data = flalc.env, 
                             permutations = 1000)
pairwise_p["Fla_LC"] <- flalc.test[["aov.tab"]][["Pr(>F)"]][1]

flaqin.dist <- vegan::vegdist(metal.hel[c(13:24,54:63),], method = "bray", diag = TRUE)
flaqin.env <- metal.env[c(13:24,54:63),]
flaqin.test <- vegan::adonis(flaqin.dist~Site, 
                             data = flaqin.env, 
                             permutations = 1000)
pairwise_p["Fla_Qin"] <- flaqin.test[["aov.tab"]][["Pr(>F)"]][1]

hupc.dist <- vegan::vegdist(metal.hel[c(25:41),], method = "bray", diag = TRUE)
hupc.env <- metal.env[c(25:41),]
hupc.test <- vegan::adonis(hupc.dist~Site, 
                             data = hupc.env, 
                             permutations = 1000)
pairwise_p["Hu_Pc"] <- hupc.test[["aov.tab"]][["Pr(>F)"]][1]

hulc.dist <- vegan::vegdist(metal.hel[c(25:36,42:53),], method = "bray", diag = TRUE)
hulc.env <- metal.env[c(25:36,42:53),]
hulc.test <- vegan::adonis(hulc.dist~Site, 
                             data = hulc.env, 
                             permutations = 1000)
pairwise_p["Hu_LC"] <- hulc.test[["aov.tab"]][["Pr(>F)"]][1]

huqin.dist <- vegan::vegdist(metal.hel[c(25:36,54:63),], method = "bray", diag = TRUE)
huqin.env <- metal.env[c(25:36,54:63),]
huqin.test <- vegan::adonis(huqin.dist~Site, 
                             data = huqin.env, 
                             permutations = 1000)
pairwise_p["Hu_Qin"] <- huqin.test[["aov.tab"]][["Pr(>F)"]][1]

pclc.dist <- vegan::vegdist(metal.hel[c(37:53),], method = "bray", diag = TRUE)
pclc.env <- metal.env[c(37:53),]
pclc.test <- vegan::adonis(pclc.dist~Site, 
                             data = pclc.env, 
                             permutations = 1000)
pairwise_p["Pc_LC"] <- pclc.test[["aov.tab"]][["Pr(>F)"]][1]

pcqin.dist <- vegan::vegdist(metal.hel[c(37:41,54:63),], method = "bray", diag = TRUE)
pcqin.env <- metal.env[c(37:41,54:63),]
pcqin.test <- vegan::adonis(pcqin.dist~Site, 
                             data = pcqin.env, 
                             permutations = 1000)
pairwise_p["Pc_Qin"] <- pcqin.test[["aov.tab"]][["Pr(>F)"]][1]

lcqin.dist <- vegan::vegdist(metal.hel[c(42:63),], method = "bray", diag = TRUE)
lcqin.env <- metal.env[c(42:63),]
lcqin.test <- vegan::adonis(lcqin.dist~Site, 
                             data = lcqin.env, 
                             permutations = 1000)
pairwise_p["LC_Qin"] <- lcqin.test[["aov.tab"]][["Pr(>F)"]][1]

p.adjust(pairwise_p, method = "BH") < 0.05

lookup <- read.csv2("metal_environment_concentrations.csv", 
                       header = TRUE, 
                       sep = ";", 
                       dec = ".", 
                       skip = 0, 
                       fill = TRUE) %>% 
  rename(Samples = X)


set.seed(19910420)
nmds <- metaMDS(metal.dist, try = 100)
nmds
str(nmds)
nmds$points
mame1 <- scores(nmds) %>% #funcion vegan similar al objeto anterior 
  as_tibble(rownames = "Samples") %>% 
  inner_join(., lookup, by = "Samples") %>% 
  mutate(Cu.Level = if_else(Copper > 10, "Higher", "Lower"))

MAME <- ggplot(mame1, aes(x = NMDS1, y = NMDS2, color = Site, size = Iron)) + 
  geom_point(aes(shape = Cu.Level)) + 
  coord_fixed() + 
  scale_color_manual(name = NULL, 
                     breaks = c("Cha", "Fla", "Hu", "Pc", "LC", "Qin"), 
                     values = c("#3B014A", "#AA006A", "#023E8A", "#95B4D2", "#269C7A", "#ACDD3C"), 
                     labels = c("Chañaral", 
                                "Flamenco", 
                                "Huasco", 
                                "Punta de Choros", 
                                "Las Cruces", 
                                "Quintero")
                     ) + 
  theme_classic()

ggsave("composite_nmds.png", plot = MAME)
```



```{r heatmap, echo=TRUE, message=TRUE, warning=TRUE}
fasta <- data.frame(names = nombres, sequences = all_of(ppe.shaseqs$Seq))
seqRFLP::dataframe2fas(fasta, "qinlc.fasta")
#Realice el alineamiento de las secuencias externamente con MUSCLE5
align <- "qinlc_aligned.fasta"
dbConn <- dbConnect(SQLite(), ":memory:")
Seqs2DB(align, type = "FASTA", dbFile = dbConn, "")
x <- dbGetQuery(dbConn, "select description from Seqs")$description
Add2DB(myData = data.frame(identifier = x, stringsAsFactors = FALSE), dbConn)
consensus <- IdConsensus(dbConn, threshold = 0.3, minInformation = 0.1)
distance.matrix <- DistanceMatrix(consensus, correction = "Jukes-Cantor", processors = NULL, verbose = TRUE)
dendrogram <- IdClusters(distance.matrix,
                         method = "ML", 
                         showPlot = TRUE, 
                         type = "dendrogram", 
                         myXStringSet = consensus, 
                         processors = NULL, 
                         verbose = TRUE)
#The selected model was TN93+G4
dbDisconnect(dbConn)
clust <- as.dendrogram(as.hclust(dendrogram)) %>% set("branches_lwd", 0.3) %>% ladderize(right = TRUE)
plot(clust)

multi.shared.ppe <- readDNAMultipleAlignment("qinlc_aligned.fasta", format = "fasta")
multi.string <- as(multi.shared.ppe, "DNAStringSet")
BrowseSeqs(multi.string, htmlFile = "Shared_PPE_multiple_alignment.html")
smatrix <- as.matrix(multi.shared.ppe) %>% rownames() %>% as.vector()
print(all(colnames(ppe.shared.asv)%in%gtools::mixedsort(smatrix, decreasing = FALSE)))
sort.abun <- ppe.shared.asv[,rownames(as.matrix(multi.shared.ppe))]
norm.hel <- heatmaply(normalize(decostand(sort.abun, method = "hellinger")), 
                      Colv = clust, 
                      Rowv = NA, 
                      main = "Shared ASVs across all sites clustered by maximum likelihood", 
                      margins = c(50, 50, 70, 0), 
                      grid_gap = 1, 
                      width = 1920, 
                      height = 1080, 
                      subplot_heights = c(0.35, 0.65), 
                      color = viridis(n = 256, 
                                      alpha = 1, 
                                      begin = 0, 
                                      end = 1, 
                                      option = "mako")
                      )
saveWidget(norm.hel, file = "hellinger_normalized_heatmap.html")
```



